# Site settings
title: Hello World!
description: Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: del Peral
user_description: "whoami" 
user_title: Data Science
email: gdelperal@gmail.com
#twitter_username:lorem_ipsum
github_username:  delperal
#gplus_username:lorem_ipsum

# Google-analytics
google-analytics:
  id: "G-24F4P3T966"

exclude: ['package.json', 'src' , 'node_modules']
