# Site settings
title: Hello World!
description: Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Phara0hms
user_description: "Pentesting is the practice of attacking various environments with the intention of discovering bugs, vulnerabilities or other security flaws, in order to prevent external attacks on those computers or systems."
user_title: Offensive Security
email: orangexcrown@gmail.com
#twitter_username:lorem_ipsum
github_username:  PharaOhms
#gplus_username:lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
